service:
  bookwarehouse:
    version: v1
    url: dubbo://${WAREHOUSE_ADDRESS:192.168.11.162:20880}/io.flomesh.demo.api.BookWarehouseService?serialization=hessian2
  bookstore:
    version: v1
    url: dubbo://${STORE_ADDRESS:192.168.11.162:20881}/io.flomesh.demo.api.BookstoreService?serialization=hessian2

dubbo:
  enabled: true
  scan:
    base-packages: io.flomesh.demo.dubbo
  protocol:
    name: dubbo
    serialization: hessian2
  config:
    multiple: false

spring:
  main:
    web-application-type: none #disable web server

grpc:
  server:
    port: -1 #disable grpc server
---
spring:
  config:
    activate:
      on-profile: dev
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20881

---
spring:
  config:
    activate:
      on-profile: prod
dubbo:
  registry:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181

