service:
  version:
    bookwarehouse: v1
    bookstore: v1
dubbo:
  enabled: true
  scan:
    base-packages: io.flomesh.demo.dubbo
  protocol:
    name: hessian
  config:
    multiple: false

spring:
  main:
    web-application-type: none #disable web server

grpc:
  server:
    port: -1 #disable grpc server
---
spring:
  config:
    activate:
      on-profile: dev
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20881

---
spring:
  config:
    activate:
      on-profile: prod
dubbo:
  registry:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181

