spring:
  profiles:
    default:
      - "dev"
      - "consul"
  application:
    name: bookstore

logging:
  level:
    root: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
---
# Dev Profile Configuration
server:
  port: 14002
grpc:
  server:
    port: 9091

spring:
  config:
    activate:
      on-profile: dev
---
# Prod Profile Configuration
server:
  port: 14001
spring:
  config:
    activate:
      on-profile: prod

