spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true



logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: DEBUG

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "gateway,health,info,prometheus"

---
# Dev Profile Configuration
server:
  port: 14000
spring:
  config:
    activate:
      on-profile: dev
grpc:
  server:
    port: 9090
---
# Prod Profile Configuration
server:
  port: 14001
spring:
  config:
    activate:
      on-profile: prod