eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    gZipContent: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  config:
    activate:
      on-profile: dev
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.default.svc.cluster.local:8761/eureka/

spring:
  config:
    activate:
      on-profile: prod