---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v2
  template:
    metadata:
      labels:
        app: httpbin
        version: v2
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "14001"
    spec:
      containers:
        - name: httpbin
          image: addozhang/httpbin-eureka:0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'eureka,prod'
            - name: IDENTITY
              value: httpbin-v2
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_TAGS
              value: "version=v2"
            - name: EUREKA_INSTANCE_METADATAMAP_VERSION
              value: v2
            - name: SPRING_CLOUD_NACOS_DISCOVERY_METADATA_VERSION
              value: v2
#            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR
#              value: 'nacos.default:8848'
#            - name: SPRING_CLOUD_NACOS_DISCOVERY_USERNAME
#              value: nacos
#            - name: SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD
#              value: nacos
#            - name: SPRING_CLOUD_CONSUL_HOST
#              value: 'consul.default'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
